/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package warehousesodp.GUI;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import warehousesodp.ItemsDB;
import warehousesodp.LoadDataToJTable;

/**
 *
 * @author Ondrej Tokar <zatokar@gmail.com, http://fuuu.sk/>
 */
public class ManagerGUI extends javax.swing.JFrame {
 private final DefaultTableModel tableModel = new DefaultTableModel();
 ItemsDB idb= new ItemsDB();
 LoadDataToJTable loadData = new LoadDataToJTable();
    /**
     * Creates new form ManagerGUI
     */
    public ManagerGUI() {
        initComponents();
        itemsTable.setModel(tableModel);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderGUI = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        productLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        amountOrderField = new javax.swing.JTextField();
        cancelOrderGUIButton = new javax.swing.JButton();
        orderGUIButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemsTable = new javax.swing.JTable();

        orderGUI.setMinimumSize(new java.awt.Dimension(395, 131));

        jLabel2.setText("Order");

        productLabel.setText("name_of_product");

        jLabel5.setText("in stock:");

        amountLabel.setText("amount");

        jLabel3.setText("Amount to order");

        amountOrderField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        cancelOrderGUIButton.setText("cancel");
        cancelOrderGUIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelOrderGUIButtonActionPerformed(evt);
            }
        });

        orderGUIButton.setText("order");
        orderGUIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderGUIButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout orderGUILayout = new javax.swing.GroupLayout(orderGUI.getContentPane());
        orderGUI.getContentPane().setLayout(orderGUILayout);
        orderGUILayout.setHorizontalGroup(
            orderGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderGUILayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(orderGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(orderGUILayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(productLabel)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(amountLabel))
                    .addGroup(orderGUILayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(orderGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(amountOrderField))
                        .addGap(18, 18, 18)
                        .addComponent(cancelOrderGUIButton)
                        .addGap(18, 18, 18)
                        .addComponent(orderGUIButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        orderGUILayout.setVerticalGroup(
            orderGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderGUILayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(orderGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(productLabel)
                    .addComponent(jLabel5)
                    .addComponent(amountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountOrderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelOrderGUIButton)
                    .addComponent(orderGUIButton))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Notification:");

        itemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item name", "Quantity", "Location"
            }
        ));
        jScrollPane1.setViewportView(itemsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(112, 112, 112))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loadData();
        if(openOrderGUI() == true){
        orderGUI.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancelOrderGUIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelOrderGUIButtonActionPerformed
        orderGUI.setVisible(false);
    }//GEN-LAST:event_cancelOrderGUIButtonActionPerformed

    private void orderGUIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderGUIButtonActionPerformed
        if (amountOrderField.getText().equals("") || amountOrderField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Fill amount first!");
        }
        else{
            Item item = idb.getItem(productLabel.getText());            
            idb.order(item.getName(),Integer.parseInt(amountOrderField.getText()),item.getLoc());
        }
    }//GEN-LAST:event_orderGUIButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerGUI().setVisible(true);
            }
        });
    }
    public void loadData(){
       loadData.loadData(idb.getItemsRS(), tableModel);
    }
    
    public boolean openOrderGUI(){
        boolean result = false;
        if (itemsTable.getSelectedRow() == -1) {
            if (itemsTable.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Suppliers table is empty.");
            } else {
                JOptionPane.showMessageDialog(this, "Select from supplier please.");
            }
        }
            else{
                    String nameToOrder = String.valueOf(itemsTable.getValueAt(itemsTable.getSelectedRow(), 0));
                    String amount = String.valueOf(itemsTable.getValueAt(itemsTable.getSelectedRow(), 1));
                    productLabel.setText(nameToOrder);
                    amountLabel.setText(amount);
                    result=true;
                    }
        return(result);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JTextField amountOrderField;
    private javax.swing.JButton cancelOrderGUIButton;
    private javax.swing.JTable itemsTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFrame orderGUI;
    private javax.swing.JButton orderGUIButton;
    private javax.swing.JLabel productLabel;
    // End of variables declaration//GEN-END:variables
}
